language: python
python:
  - "3.5"
  - "3.6"
  # - "3.7" not available on travis as OpenSSL 1.0.2+ is not available on Ubuntu Trusty

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - python setup.py develop
  - pip freeze

script:
  - python -m pytest --cov=cdcam tests

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls || echo "failed"; fi

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: mSUdus8xufbcjiRZjRjIS4fmRJaa8lYOlNZcvE+P0LpXE6vBopmzSR0/LeE1ZuoZU44V6wSEOkd+vGXMVPmRyFG0WF8x7T8NkRVuPqmjS0ziuoD+ib67R8rU49B6htUvzexiye7SwZYR6ldOCGY7W25/RH6PlzgtIQKyHBTKFPfgjzrHoS8ST+yhNxSNbW2pfPXTu39QNA1Dlr3VzDKaIjh5Zgu5BOGkbvemE7VpZUkR5rXeJFfh+PQF/UdSuDYeFS5XF05mAdP/16ZSu/LEMZZ2Kam2gSwRr4KjH1uW6WsA4Gk0G68uG8m3Zv5iqFizVMIJYPg+ym4UF/uzezFi/eLy3OnuOEKyKnwy4KzZwzA/ihx5gSuzEJNf2wyn3mwr8ymbhibRw8EDYQoiPl8uxPs4LAcym48XD3rjA0ACFSrDZI7omc9yGrWAkw5aDuDRlk5755TjMLXvIeUr2PIvMXlHS47GbXJKAfB8sbeqB7TfmTEE2Tei2cVGSEzKKUFGQ4HRe4C/KyCjrwd8YJ/+66f8kpqoP8Gp2MGTfGK10xsyrPX9BybFls4rYfS6AX9K6mbUkh3HSzNGY/9sl7U1OYJeNqhK7dkuntGOqJ1zpbf3mE1qMmAh01feOJvFNoEJXsZivmvYnHtry0YlfuYE91rwAHNWv+06D59gHegcrwA=
  on:
    tags: true
  skip_existing: true

